"""create initial schema

Revision ID: c480fcb39322
Revises:
Create Date: 2026-07-10 22:18:05.073060

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c480fcb39322"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_prices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column(
            "input_cost_per_1k_tokens",
            sa.Numeric(precision=10, scale=6),
            nullable=False,
        ),
        sa.Column(
            "output_cost_per_1k_tokens",
            sa.Numeric(precision=10, scale=6),
            nullable=False,
        ),
        sa.Column("provider_name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_prices")),
    )
    op.create_index(
        op.f("ix_model_prices_model_name"), "model_prices", ["model_name"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_key", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column(
            "daily_budget_usd", sa.Numeric(precision=10, scale=6), nullable=False
        ),
        sa.Column("requests_per_minute", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_user_key"), "users", ["user_key"], unique=True)
    op.create_table(
        "requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("task_type", sa.String(length=100), nullable=False),
        sa.Column("policy", sa.String(length=100), nullable=False),
        sa.Column("selected_model", sa.String(length=100), nullable=False),
        sa.Column("prompt_hash", sa.String(length=64), nullable=False),
        sa.Column("cache_key", sa.String(length=128), nullable=True),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("fallback_used", sa.Boolean(), nullable=False),
        sa.Column("primary_model", sa.String(length=100), nullable=True),
        sa.Column("fallback_model", sa.String(length=100), nullable=True),
        sa.Column("estimated_input_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_output_tokens", sa.Integer(), nullable=False),
        sa.Column(
            "estimated_cost_usd", sa.Numeric(precision=12, scale=8), nullable=False
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error_type", sa.String(length=100), nullable=True),
        sa.Column("output_preview", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_requests_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requests")),
    )
    op.create_index("ix_requests_cache_hit", "requests", ["cache_hit"], unique=False)
    op.create_index(
        "ix_requests_policy_created_at",
        "requests",
        ["policy", "created_at"],
        unique=False,
    )
    op.create_index("ix_requests_task_type", "requests", ["task_type"], unique=False)
    op.create_index(
        "ix_requests_user_id_created_at",
        "requests",
        ["user_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_requests_user_id_created_at", table_name="requests")
    op.drop_index("ix_requests_task_type", table_name="requests")
    op.drop_index("ix_requests_policy_created_at", table_name="requests")
    op.drop_index("ix_requests_cache_hit", table_name="requests")
    op.drop_table("requests")
    op.drop_index(op.f("ix_users_user_key"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_model_prices_model_name"), table_name="model_prices")
    op.drop_table("model_prices")
    # ### end Alembic commands ###
